// <auto-generated />
using System;
using Malvin_Lopez_AP1_P2.Components.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Malvin_Lopez_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715023045_CrearEntrada")]
    partial class CrearEntrada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Entrada", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("EntradaId");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("EntradaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("EntradaDetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaDetalle");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripcion = "Maní",
                            EsCompuesto = false,
                            Existencia = 100m,
                            Peso = 10.00m
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripcion = "Pistachos",
                            EsCompuesto = false,
                            Existencia = 100m,
                            Peso = 5.00m
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripcion = "Almendras",
                            EsCompuesto = false,
                            Existencia = 100m,
                            Peso = 20.00m
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripcion = "Frutos Mixtos 200gr",
                            EsCompuesto = true,
                            Existencia = 0m,
                            Peso = 200.00m
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripcion = "Frutos Mixtos 400gr",
                            EsCompuesto = true,
                            Existencia = 0m,
                            Peso = 400.00m
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripcion = "Frutos Mixtos 600gr",
                            EsCompuesto = true,
                            Existencia = 0m,
                            Peso = 600.00m
                        });
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.EntradaDetalle", b =>
                {
                    b.HasOne("Malvin_Lopez_AP1_P2.Components.Models.Entrada", "Entrada")
                        .WithMany("EntradaDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Malvin_Lopez_AP1_P2.Components.Models.Producto", null)
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Entrada", b =>
                {
                    b.Navigation("EntradaDetalle");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Producto", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
