// <auto-generated />
using System;
using Malvin_Lopez_AP1_P2.Components.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Malvin_Lopez_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715001557_CrearTablaEntradas")]
    partial class CrearTablaEntradas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Entrada", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradaId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradaDetalles");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.EntradaDetalle", b =>
                {
                    b.HasOne("Malvin_Lopez_AP1_P2.Components.Models.Entrada", "Entrada")
                        .WithMany("EntradaDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("Malvin_Lopez_AP1_P2.Components.Models.Entrada", b =>
                {
                    b.Navigation("EntradaDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
